# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header:  $

# ebuild generated by hackport 0.2.15

EAPI=4

CABAL_FEATURES="bin lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Fast, packed, strict storable arrays with a list interface like ByteString"
HOMEPAGE="http://www.haskell.org/haskellwiki/Storable_Vector"
SRC_URI="http://hackage.haskell.org/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="=dev-haskell/non-negative-0.1*
		>=dev-haskell/quickcheck-1
		<dev-haskell/quickcheck-3
		>=dev-haskell/syb-0.1
		<dev-haskell/syb-0.4
		=dev-haskell/transformers-0.2*
		>=dev-haskell/utility-ht-0.0.5
		<dev-haskell/utility-ht-0.1
		>=dev-lang/ghc-6.8.2"
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.6"
